### ISSUE TITLE
failed to execute goal org.codehaus.mojo:jaxws-maven-plugin1.9:wsgn

### ISSUE THREAD

**Issue by Nihal-Gupta** [mojohaus/jaxws-maven-plugin#10]
<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<version>1.9</version>
				<executions>
					<execution>
					 <id>wsgen-from-jdk</id>
						<goals>
							<goal>wsgen</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					
					<sei>
						org.opensoa.repository.ws.RepositoryWebService
					</sei>
					
					<genWsdl>true</genWsdl>
					<sourceDestDir>E:\Nihal\openSOAsrcnoclass\openSOAsrc\repository\core\src\main\java\org\opensoa\repository\ws</sourceDestDir>
					<verbose>true</verbose>
				</configuration>

				
				<dependencies>
					
					<dependency>
						<groupId>javax.jws</groupId>
						<artifactId>jsr181-api</artifactId>
						<version>1.0-MR1</version>
					</dependency>

				</dependencies>
			</plugin>

**Comment by andham** [comment]
You need to provide much more info, the error output in the console for example. Also, a standalone test project would also help to reproduce.
But, I would start by upgrading to v2.4 of the plugin. v1.9 is extremely old and there will be no fix for that.

**Comment by andham** [comment]
Closing. Please open a new ticket if the problems persists with version 2.4+!
