### ISSUE TITLE
wsimport ignores <wsdlLocation> with "*" if no <wsdlFiles> are specified

### ISSUE THREAD

**Issue by lathspell** [mojohaus/jaxws-maven-plugin#12]
According to its documentation, <wsdlFiles> is not required if all *.wsdl files in <wsdlDirectory> should be imported in the goal "wsimport".

Contrary to that, the <wsdlLocation>/wsdl/*</wsdlLocation> is ignored when no wsdlFiles are specified!
The "[INFO] jaxws:wsimport args:" output does not show "-wsdllocation" in that case.

The bug seems to be in WsImportMojo.java where processLocalWsdlFiles() calls getRelativePath() to get a relative path as argument for getWsImportArgs(relPath). The getRelativePath() method internally iterates through the object attribute wsdlFiles which is NULL if <wsdlFiles> is not specified.

**Comment by andham** [comment]
So this one is a bit tricky. One could argue that the current behavior is intended, where the path for the wsdl files is treated as absolut when they are not specified. The docs isn't clear on this other than "all .wsdl files in the wsdlDirectory will be used". It doesn't say if the paths are treated as absolute or relative. Also, changing this behavior could break some existing builds.

However, it think it would be safe to change as anyone who has specified wsdlLocation would like that to be used. I'll go ahead and change this
