### ISSUE TITLE
[WARNING] -encoding may not supported on older JDKs.

### ISSUE THREAD

**Issue by mheitnrw** [mojohaus/jaxws-maven-plugin#14]
Hello dear jaxws-maven-plugin developers,

Is there a way to get rid of the warning "-encoding may not supported on older JDKs."?
With the following plugin configuration the warning is still issued:

```
                    <args>
                        <arg>-encoding UTF-8</arg>
                    </args>
```

Kind regards
Michael

**Comment by michael-o** [comment]
I have found there reference: https://github.com/mojohaus/jaxws-maven-plugin/search?l=java&q=encoding&utf8=%E2%9C%93

Can you provide a PR for that?

**Comment by mheitnrw** [comment]
Sorry michael-o, I don't understand. PR means pull request? If so, I do not for what to provide a pull request.

**Comment by michael-o** [comment]
Lets rephrase, what do you expect to see and what JDK versions are affected?

**Comment by mheitnrw** [comment]
Thanks for rephrasing!

It says: "[WARNING] -encoding may not supported on older JDKs. Use <args> to bypass this warning if you really want to use it."

I have "encoding" in "args". So I expect no warning. JDK is Oracle 1.8.0_102.

**Comment by michael-o** [comment]
Just checked, `encoding` has been added back in 2011-10: https://github.com/gf-metro/jaxws/commit/0318f69313236152cdc8e5f0ecd321b081969afc, five years ago. I think it is safe to drop this warning.

**Comment by andham** [comment]
I checked and Oracle JDK 1.7.0_80 does not support the -encoding parameter. It is supported by Oracle JDK 1.8 though (checked 1.8.0_40 and 1.8.0_112).

**Comment by andham** [comment]
As long as we support JDK 7 we can't change this. Closing.

**Comment by phax** [comment]
Can't the warning only be emitted if the current Java version is 1.7 or less?

**Comment by andham** [comment]
A basic principle with Maven is that builds should be portable. So you should get the same end result regardless of if (for example) JDK 1.7 or JDK 1.8 is used (that is, assuming the target is Java 7). So any checks of the JDK used affecting this is not a good thing.
So in this case, if you know that JDK 8 will be used for the build (you could have an enforcer rule for that) you should use the suggest args parameter solution. Now I see that the first comment in this thread says that also causes the warning message. That shouldn't be the case though. I'll look into that.

**Comment by andham** [comment]
I see there is an issue here. The plugin's encoding param defaults to project.build.sourceEncoding, which typically is/should be set. SO even if you don't specify encoding configuration it is implicitly set by this default config. The plugin therefore tries to configure jaxws with the -encoding param, which emits the warning message. Even if encoding is specified via args param.
What could happen here as well is that a different encoding is specified via args than project.build.sourceEncoding specifies. For JDK 1.8+ encoding config is applied twice; not sure which of them will be used. Not good, even if the likelihood of having different encoding via args than project.build.sourceEncoding is low (shouldn't really be the case as you will have mixed encoding in source files).

**Comment by andham** [comment]
I've checked the code and the reported issue should only occur if an executable is specified, either directly via the executable param or by specifying JDK toolchain. Could @mheitnrw please confirm that this is the case?
To solve this we need to decide how to handle arguments that may not be supported by a JDK (or external wsimport/wsgen executable). There is no generic way to ask for, for example, JDK or JAX-WS version to determine if argument is supported. And then for encoding we also need to fix the possible issue of encoding being specified twice (see my comment above).

**Comment by mheitnrw** [comment]
I confirm that I use a ~/.m2/toolchains.xml with one entry for a Oracle 1.8 JDK.

**Comment by andham** [comment]
As we have now up'ed the requirement to Java 8 I think it would be ok to remove this warning.
While now re-reading this full thread I see that i brought up a separate issue where the encoding arg could be applied twice, which is a separate issue and not what this report initially is about. I therefore think we should remove the warning as Java 8 is now required and the issue about encoding being applied twice be moved outside of this ticket.

**Comment by andham** [comment]
The implemented change should now allow the configured "encoding" to be used even when a different executable is configured, without the need to use "args". "args" should not even be used as it would add two (2) -encoding options to the jax-ws tool.
