### ISSUE TITLE
WsImportMojo: warning "cannot find file for" for test artefacts

### ISSUE THREAD

**Issue by phax** [mojohaus/jaxws-maven-plugin#15]
This warning (like 587 in `getWSDLFiles`) should not be emitted for artefacts that use scope `test` or `provided` or where `optional=true` is set.

See `Artifact.isOptional()` and `Artifact.SCOPE_TEST.equals( artifact.getScope() )` resp. `Artifact.SCOPE_PROVIDED.equals( artifact.getScope() )`.
If you want, I can provide a PR

**Comment by andham** [comment]
I don't understand. All (direct) dependencies of a project should be accessible regardless of scope, so why shouldn't this warning be emitted for test, provided, and optional dependencies?

**Comment by phax** [comment]
An artefact with scope 'test' is not in the classpath except you run unit tests (`mvn test`) so a warning on an artifact when this is NOT run in test, is annoying.

Every build warns that an artefact file cannot be found otherwise.

**Comment by andham** [comment]
But I don't understand why the artifact can't be found. Can you provide a test project for this scenario?

**Comment by phax** [comment]
[sample-project.zip](https://github.com/mojohaus/jaxws-maven-plugin/files/1124453/sample-project.zip)
Here's a stripped down version - not as simple as possible but usable.
Basically the problem is the "dnsjava" artefact referenced in the pom.xml.
When you run `mvn generate-sources` the second time it is very obivous...

**Comment by andham** [comment]
OK, I see the issue. Actually I think that there is a bug in the code where all dependencies are used on the Classloader classpath when getting the wsdl files. Test scope dependencies should only be used in wsimport-test, not in wsimport.
