### ISSUE TITLE
Question: How to enable binding extensions?

### ISSUE THREAD

**Issue by OrangeDog** [mojohaus/jaxws-maven-plugin#22]
Nobody here may know, but support for `wsimport` itself is hard to find.

If I wanted to use binding extensions, such as from the schemas `http://java.sun.com/xml/ns/jaxb/xjc` or `http://jaxb2-commons.dev.java.net/basic/inheritance`, how do I actually enable them, since `jaxws:bindings` doesn't appear to support a `extensionBindingPrefixes` attribute?

See also [this SO question](http://stackoverflow.com/q/39640430/476716).

**Comment by andham** [comment]
Closing as no one has been able to answer.

**Comment by OrangeDog** [comment]
@andham how is that helpful?
At least leave it open as a task for someone to go find out.

**Comment by andham** [comment]
@OrangeDog This is mainly intended as an issue tracker, not a place for questions. Use the users mailing list (or stackoverflow) for that. Also, I take you question is more about wsimport than this actual maven plugin.

**Comment by OrangeDog** [comment]
Oh sorry, it's been so long since I asked I forgot it wasn't actually this project.
