### ISSUE TITLE
wsimport fails with JDK 8: Failed to read schema document 'xjc.xsd', because 'file' access is not allowed due to restriction set by the accessExternalSchema property

### ISSUE THREAD

**Issue by hboutemy** [mojohaus/jaxws-maven-plugin#4]
see http://stackoverflow.com/questions/23011547/webservice-client-generation-error-with-jdk8
and https://java.net/jira/browse/JAX_WS_COMMONS-129

building jaxws-maven-plugin with JDK 8 shows this exact issue

**Comment by hboutemy** [comment]
reference documentation: https://jaxp.java.net/1.5/1.5.0/ReleaseNotes.html and https://jaxp.java.net/1.5/JAXP1.5Guide.html#JAXP1.5Documentation%2CGuide-7.Usingtheproperties

should we add
    <vmArgs>
        <vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
    </vmArgs>
as default value in jaxws-maven-plugin?
or simply add as an example?

**Comment by andham** [comment]
I think we should align with how it is handled by jaxb2-maven-plugin.

**Comment by andham** [comment]
Somehow this is handled automatically in the jaxb2-m-p case, either by the plugin or by some library:
> [DEBUG] [SchemaGen]: mar 07, 2017 12:34:23 EM com.sun.xml.xsom.parser.JAXPParser allowFileAccess
> FIN: Property "http://javax.xml.XMLConstants/property/accessExternalSchema" is supported and has been successfuly set by used JAXP implementation.

**Comment by andham** [comment]
In a local test I upgraded the jaxws-m-p to use v2.2.10 of jaxws-tools and v0.11.1 of jaxb2-basics. Then it works with Oracle JDK 1.8b112 without having to specify the vm arg.

**Comment by andham** [comment]
This has been fixed as part of #8. No additional config args are needed with JDK 8.

**Comment by andham** [comment]
Until v2.5 is released, it is possible to make v2.4.x work with JDK 8 by upgrading one of its dependencies like this:

>				<plugin>
>					<groupId>org.codehaus.mojo</groupId>
>					<artifactId>jaxws-maven-plugin</artifactId>
>					<version>2.4.1</version>
>					<dependencies>
>						<dependency>
>							<groupId>com.sun.xml.ws</groupId>
>							<artifactId>jaxws-tools</artifactId>
>							<version>2.2.10</version>
>						</dependency>
>					</dependencies>
>				</plugin>

**Comment by CassandraTis** [comment]
@andham Not working for me. Still have the same issue

**Comment by trackitecture** [comment]
Hello
I am trying to generate the source for a webservice. I am using 
mvn -version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
Maven home: ...../apache-maven-3.5.4
Java version: 10.0.2, vendor: Oracle Corporation, runtime: D:\dev\java\jdk-10.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

The parent-pom contains:
<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<java.version>1.8</java.version>
</properties>

I get the following error:
[ERROR] Failed to execute goal org.codehaus.mojo:jaxws-maven-plugin:2.5:wsimport (generate-my-soap-service-code) on project platform-my-soap-service: Invocation of com.sun.tools.ws.wscompile.WsimportTool failed - check output -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:jaxws-maven-plugin:2.5:wsimport (generate-my-soap-service-code) on project platform-my-soap-service: Invocation of com.sun.tools.ws.wscompile.WsimportTool failed - check output


I hope this will help
