### ISSUE TITLE
How do I specify which -source and -target versions that javac should use?

### ISSUE THREAD

**Issue by RichoDemus** [mojohaus/jaxws-maven-plugin#42]
So I'm using jaxws-maven-plugin to generate some classes from a wsdl and I'm running JDK8 but would like the compiled classes to be compatible with java 7 and it seems like this plugin does not use maven-compiler-plugin to compile and thus ignores the configuration I've set there

**Comment by andham** [comment]
Please use users mailing list for questions.
http://www.mojohaus.org/jaxws-maven-plugin/mail-lists.html
