### ISSUE TITLE
Absolute path when generating classes.

### ISSUE THREAD

**Issue by JaviKx2** [mojohaus/jaxws-maven-plugin#61]
It works fine when I am developing in my local env, but It doesn't when I deploy the artifact because of the absolute path pointing to my wsdl files. I need to get a relative path.

Produced code looks like this:
 static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/workspace/my-project/src/main/resources/wsdl/MyOwnWSDL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATEINTERACTIONWS_WSDL_LOCATION = url;
        CREATEINTERACTIONWS_EXCEPTION = e;
    }

**Comment by andham** [comment]
There should be a constructor that takes the URL as an argument which you should use in this case.

**Comment by JaviKx2** [comment]
Is there no way of setting a relative path using the plugin directly?

**Comment by andham** [comment]
Don't think so. But have a look at the underlying JDK tooling and if you see support for this there it should be possible.

**Comment by JaviKx2** [comment]
Well, It was definitely possible.

On the jaxws-maven-plugin specific configuration It is needed to follow this structure, not necessarily with this exactly order, but with all these labels:

<configuration>
        <wsdlDirectory>${project.basedir}/src/main/resources/wsdl</wsdlDirectory>
	<wsdlLocation>/wsdl/*</wsdlLocation>
	<wsdlFiles>
		<wsdlFile>file1.wsdl</wsdlFile>
		<wsdlFile>file2.wsdl</wsdlFile>
		<wsdlFile>file3.wsdl</wsdlFile>
                ...
	</wsdlFiles>
        ...
</configuration>

This way the generated code is valid for any environment.
